# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKZJ6ziWwLuB8ga-rT2uEH9QvMGE8GQ4
"""

!pip install geemap

import ee, geemap
import folium
from folium.plugins import Fullscreen, MeasureControl

ee.Authenticate()
ee.Initialize(project='hidro-457516')

gaul1 = ee.FeatureCollection('FAO/GAUL/2015/level1')
meta = (gaul1
        .filter(ee.Filter.eq('ADM0_NAME', 'Colombia'))
        .filter(ee.Filter.eq('ADM1_NAME', 'Meta'))
        .geometry())

gfc = ee.Image('UMD/hansen/global_forest_change_2023_v1_11')

treecover2000 = gfc.select('treecover2000')
lossyear = gfc.select('lossyear')

forest2000 = treecover2000.gte(30)

loss_2001_2023 = lossyear.gte(1).And(lossyear.lte(23))

forest2023 = forest2000.And(loss_2001_2023.Not())

vis_tree = {'min': 0, 'max': 100, 'palette': ['red','orange','yellow','green']}
vis_bin_green = {'palette': ['#00A65A']}
vis_loss = {'min': 0, 'max': 23,
            'palette': ['#ffffcc','#ffeda0','#fed976','#feb24c','#fd8d3c',
                        '#fc4e2a','#e31a1c','#b10026']}

left_img  = treecover2000.clip(meta)
right_img = forest2023.updateMask(forest2023).clip(meta)

m = geemap.Map(center=[3.64, -73.63], zoom=7)

left_layer  = geemap.ee_tile_layer(left_img,  vis_tree,     name='Cobertura 2000 (%)')
right_layer = geemap.ee_tile_layer(right_img, vis_bin_green, name='Bosque remanente (2000→2023)')

m.split_map(left_layer=left_layer,
            right_layer=right_layer,
            left_label='Bosque (2000)',
            right_label='Bosque remanente (2023)')

m.addLayer(meta, {'color': 'white'}, 'Límite Meta', shown=True)

left_layer  = geemap.ee_tile_layer(left_img,  vis_tree,     name='Cobertura 2000 (%)')
right_layer = geemap.ee_tile_layer(right_img, vis_bin_green, name='Bosque remanente (2000→2023)')

m.split_map(left_layer=left_layer,
            right_layer=right_layer,
            left_label='Bosque (año 2000)',
            right_label='Bosque remanente (hasta 2023)')

m.addLayer(meta, {'color': 'white'}, 'Límite Meta', shown=True)

m.add_legend(title='Cobertura 2000 (%)', legend_dict={
    'Bajo (0-25)': '#ff0000',
    'Medio (25-50)': '#ffa500',
    'Alto (50-75)': '#ffff00',
    'Muy alto (75-100)': '#008000'
})

loss_img = lossyear.updateMask(lossyear).clip(meta)
m.addLayer(loss_img, vis_loss, 'Pérdida 2001–2023')

m